# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nebari-dia-adx',
                'doc_host': 'https://equinor.github.io',
                'git_url': 'https://github.com/equinor/nebari-dia-adx',
                'lib_path': 'nebari_dia_adx'},
  'syms': {'nebari_dia_adx.core': {'nebari_dia_adx.core.foo': ('core.html#foo', 'nebari_dia_adx/core.py')}}}
